name: Build

on:
  pull_request:
    branches:
      "main"

  push:
    branches:
      "main"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - run: ./gradlew clean test